### ISSUE TITLE
Unrecognized font family 'FontAwesome'

### ISSUE THREAD

**Issue by p4tric** [simwx123/moviesApp#1]
Hi,

Upon running code in IOS simulator, the movie list loads fine. But upon clicking on one of the movie items, I got this error:

![image (1)](https://user-images.githubusercontent.com/1955349/72309677-9b90da80-36ba-11ea-8aef-c12246dabd69.png)
![image](https://user-images.githubusercontent.com/1955349/72309678-9c297100-36ba-11ea-9383-446313752c24.png)

**Comment by p4tric** [comment]
I still get this problem after pulling and running code.

**Comment by simwx123** [comment]
Hi p4tric, I run simulator from the Xcode everything is fine. A suggestion to you is after pulling 
and "npm install" try go to the moviesApp/ios and type "pod install".

**Comment by p4tric** [comment]
Hi,
I did a fresh clone, did npm install and goto moviesApp/ios and typed "pod install". I ran simulator from Xcode and i got this errors from Build:

![image](https://user-images.githubusercontent.com/1955349/72422147-db3feb00-37bc-11ea-92f8-cf94bd2617d7.png)

**Comment by simwx123** [comment]
> Hi,
> I did a fresh clone, did npm install and goto moviesApp/ios and typed "pod install". I ran simulator from Xcode and i got this errors from Build:
> 
> ![image](https://user-images.githubusercontent.com/1955349/72422147-db3feb00-37bc-11ea-92f8-cf94bd2617d7.png)

I suspect is the xcode version, if you are using xcode 10 then try do this.
1.) In Xcode, go to File->Project/Workspace settings.
2.) Change the build system to Legacy Build system.
3.) command+shift+k
4.) command+b
5.) Click run button

**Comment by p4tric** [comment]
Xcode version is:

![image](https://user-images.githubusercontent.com/1955349/72488426-e7bf5480-384b-11ea-8010-03cbbaa7e23b.png)

But I did the instruction eventhough im not in xcode 10. It worked and runs the movieApp.

**Comment by simwx123** [comment]
> Xcode version is:
> 
> ![image](https://user-images.githubusercontent.com/1955349/72488426-e7bf5480-384b-11ea-8010-03cbbaa7e23b.png)
> 
> But I did the instruction eventhough im not in xcode 10. It worked and runs the movieApp.

Simply remove duplicate reference fonts in "Copy Bundle Resources" NOT in "[CP] Copy Pods Resources".
